coverage:
  range: "60...80"
  status:
    patch:
      default:
        threshold: 1
  project:
    default:
      informational: true
    app: # declare a new status context "tests"
      target: 100% # we always want 100% coverage here
      paths: "pmm-app/src/"
    toolkit: # declare a new status context "app"
      paths: "pmm-app/grafana-toolkit"
