coverage:
  range: "60...80"
  status:
    patch:
      default:
        threshold: 1
  project:
    default:
      informational: true
    app: # declare a new status context "tests"
      target: 100% # we always want 100% coverage here
      paths: "pmm-app/src/"
    toolkit: # declare a new status context "app"
      paths: "pmm-app/grafana-toolkit"
  comment:
    layout: "reach, diff, flags, files"
    behavior: default
    require_changes: false  # if true: only post the comment if coverage changes
    require_base: no        # [yes :: must have a base report to post]
    require_head: yes       # [yes :: must have a head report to post]
